### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by john-french** [gmit-sweng-20/ca5-bdd-tdd-cycle2-rachelmcclelland#6]
@rachelmcclelland 
- Would be good to verify what happens after the `get` https://github.com/gmit-sweng-20/ca5-bdd-tdd-cycle2-rachelmcclelland/blob/33001057259963f97ded67d9b7c7274ae9fbf6a3/rottenpotatoes/spec/controllers/movies_controller_spec.rb#L18, e.g. is correct template rendered, is correct information available to populate it.
- Other tests are very good, well done.

Please close this issue to acknowledge receipt of feedback.

**Comment by rachelmcclelland** [comment]
Thanks for the feedback John
